name: Build KernelSU Kernel Module

on:
  workflow_call:
    inputs:
      kmi:
        description: 'KMI version'
        required: true
        type: string
      ddk_release:
        description: 'DDK release version'
        required: false
        default: '20250825'
        type: string
      kernelsu_tag:
        description: 'KernelSU release tag or commit'
        required: false
        default: 'main'
        type: string

jobs:
  build-kernelsu-ko:
    name: Build kernelsu.ko for ${{ inputs.kmi }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk-dev:${{ inputs.kmi }}-${{ inputs.ddk_release }}
      options: --privileged

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        path: ksuinit

    - name: Clone KernelSU repository
      run: |
        echo "Cloning KernelSU from https://github.com/tiann/KernelSU"
        git clone https://github.com/tiann/KernelSU kernelsu
        cd kernelsu
        
        # Checkout specified tag/commit if provided
        if [ "${{ inputs.kernelsu_tag }}" != "" ] && [ "${{ inputs.kernelsu_tag }}" != "main" ]; then
          echo "Checking out KernelSU tag/commit: ${{ inputs.kernelsu_tag }}"
          git checkout ${{ inputs.kernelsu_tag }}
        fi
        
        echo "=== KernelSU Repository Info ==="
        git log --oneline -5
        echo "Current commit: $(git rev-parse HEAD)"

    - name: Build kernelsu.ko
      run: |
        cp ksuinit/.github/scripts/Makefile kernelsu/kernel/Makefile

        cd kernelsu/kernel

        echo "=== Building kernelsu.ko for KMI: ${{ inputs.kmi }} ==="

        KSU_GIT_VERSION=$(git rev-list --count HEAD) make
        
        echo "=== Build completed ==="

        # Create output directory in GitHub workspace
        mkdir -p /github/workspace/out
        
        # Copy with KMI-specific naming
        OUTPUT_NAME="kernelsu-${{ inputs.kmi }}.ko"
        cp kernelsu.ko "/github/workspace/out/$OUTPUT_NAME"
        
        echo "Copied to: /github/workspace/out/$OUTPUT_NAME"
        ls -la "/github/workspace/out/$OUTPUT_NAME"
        echo "Size: $(du -h "/github/workspace/out/$OUTPUT_NAME" | cut -f1)"
        llvm-strip -d "/github/workspace/out/$OUTPUT_NAME"
        echo "Size after stripping: $(du -h "/github/workspace/out/$OUTPUT_NAME" | cut -f1)"

    - name: Upload kernelsu.ko artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernelsu-${{ inputs.kmi }}.ko
        path: /github/workspace/out/kernelsu-${{ inputs.kmi }}.ko
